workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        BUNDLE_ID: \"com.anan8.delegate\"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Clean and setup
        script: |
          flutter clean
          flutter pub get

      - name: Create iOS project with correct platform
        script: |
          rm -rf ios
          flutter create --platforms=ios --org com.anan8.delegate .
          sed -i '' 's/platform :ios, .*/platform :ios, \"14.0\"/g' ios/Podfile
          plutil -replace MinimumOSVersion -string 14.0 ios/Runner/Info.plist
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/g' ios/Runner.xcodeproj/project.pbxproj

      - name: Create ExportOptions.plist
        script: |
          cat > ExportOptions.plist << 'EOL'
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
    <key>compileBitcode</key>
    <false/>
    <key>method</key>
    <string>development</string>
    <key>provisioningProfiles</key>
    <dict>
        <key>com.anan8.delegate.delegate</key>
        <string>iOS Team Provisioning Profile: *</string>
    </dict>
    <key>signingStyle</key>
    <string>manual</string>
    <key>stripSwiftSymbols</key>
    <true/>
    <key>thinning</key>
    <string>&lt;none&gt;</string>
</dict>
</plist>
EOL
          echo \"ExportOptions.plist created\"

      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign --export-options-plist=ExportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa
