workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        BUNDLE_ID: \"com.anan8.delegate\"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Build IPA
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
