workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        BUNDLE_ID: \"com.anan8.delegate\"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Clean and setup
        script: |
          flutter clean
          flutter pub get

      - name: Create iOS project with correct platform
        script: |
          rm -rf ios
          flutter create --platforms=ios --org com.anan8.delegate .
          sed -i '' 's/platform :ios, .*/platform :ios, \"14.0\"/g' ios/Podfile
          plutil -replace MinimumOSVersion -string 14.0 ios/Runner/Info.plist

      - name: Build iOS App Bundle (no signing needed)
        script: |
          flutter build ios --release --no-codesign --simulator
          echo \"✅ iOS App Bundle built successfully\"

      - name: List build artifacts
        script: |
          echo \"Build artifacts:\"
          find build/ios -name \"*.app\" -o -name \"*.xcarchive\" | head -10
          ls -la build/ios/

    artifacts:
      - build/ios/
      - build/ios/iphoneos/Runner.app
      - build/ios/archive/Runner.xcarchive
