workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        BUNDLE_ID: \"com.anan8.delegate\"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Clean and setup
        script: |
          flutter clean
          flutter pub get

      - name: Create iOS project
        script: |
          rm -rf ios
          flutter create --platforms=ios --org com.anan8.delegate .

      - name: Build iOS without CocoaPods
        script: |
          flutter build ios --release --no-codesign --no-pub --verbose

      - name: Check build results
        script: |
          if [ -d \"build/ios\" ]; then
            echo \"✅ Build successful! Files:\"
            find build/ios -name \"*.app\" 2>/dev/null || echo \"No .app files but build directory exists\"
          else
            echo \"❌ Build failed - no build directory\"
            exit 1
          fi

    artifacts:
      - build/ios/
      - build/ios/**/*.app
