workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.anan8.delegate"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Create iOS directory if missing
        script: |
          if [ ! -d "ios" ]; then
            echo "Creating iOS directory..."
            flutter create --platforms=ios --org com.anan8.delegate .
          fi

      - name: Set iOS deployment target to 13.0
        script: |
          if [ -f "ios/Podfile" ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/g' ios/Podfile
          fi

          if [ -f "ios/Runner/Info.plist" ]; then
            plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign --verbose

      - name: List build artifacts
        script: |
          ls -la build/ios/ipa/

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - email: ahmadalhmoud717@gmail.com
        notify:
          success: true
          failure: true
