name: Build iOS IPA - Final Solution

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Clean and prepare
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Get dependencies
        run: flutter pub get

      - name: Recreate iOS project with proper platform
        run: |
          # احذف مجلد ios بالكامل
          rm -rf ios

          # أنشئ مشروع iOS جديد
          flutter create --platforms=ios --ios-language=swift --org com.yourcompany .

          # إجبار iOS 13.0 في جميع الملفات
          if [ -f "ios/Podfile" ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/g' ios/Podfile
          fi

          if [ -f "ios/Runner/Info.plist" ]; then
            plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist
          fi

          if [ -f "ios/Runner.xcodeproj/project.pbxproj" ]; then
            sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj
          fi

          echo "✅ iOS project recreated with platform 13.0"

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
