name: Build iOS IPA - Simple Approach

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Clean and prepare
        run: |
          flutter clean
          rm -rf ios build

      - name: Build IPA with Flutter only
        run: |
          # دع Flutter يتعامل مع كل شيء تلقائياً
          flutter pub get
          flutter build ipa --release --no-codesign

          echo "✅ Build completed using Flutter's automatic setup"

      - name: Upload success artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
