name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Let Flutter generate iOS files
        run: |
          # تنظيف وإعادة إنشاء ملفات iOS تلقائياً
          flutter clean
          flutter pub get

          # تأكد من وجود مجلد ios
          if [ ! -d "ios" ]; then
            echo "Creating iOS directory..."
            flutter create --platforms=ios --ios-language=swift .
          fi

          # تحديث Podfile تلقائياً
          flutter build ios --no-codesign --release 2>/dev/null || true

      - name: Fix iOS deployment target
        run: |
          # تأكد من iOS 13.0 في Podfile
          if [ -f "ios/Podfile" ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/g' ios/Podfile
            echo "Updated Podfile:"
            head -3 ios/Podfile
          fi

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
