name: Build Unsigned Flutter iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter manually
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.13.0 --depth 1
          export PATH="$PWD/flutter/bin:$PATH"
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no-code-sign)
        run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa && zip -r app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ios/ipa/app.ipa
