name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Explore project structure
        run: |
          echo "=== Project Structure ==="
          ls -la
          echo "=== Looking for key files ==="
          find . -name "pubspec.yaml" -o -name "ios" -o -name "Podfile" 2>/dev/null || echo "No key files found"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Find project root
        id: find-root
        run: |
          if [ -f "./pubspec.yaml" ]; then
            echo "PROJECT_ROOT=." >> $GITHUB_ENV
          else
            # ابحث عن مجلد يحتوي على pubspec.yaml
            PROJECT_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \; | head -1)
            if [ -n "$PROJECT_DIR" ]; then
              echo "PROJECT_ROOT=$PROJECT_DIR" >> $GITHUB_ENV
            else
              echo "ERROR: No Flutter project found!"
              exit 1
            fi
          fi
          echo "Project root: $PROJECT_ROOT"

      - name: Get dependencies
        run: |
          cd ${{ env.PROJECT_ROOT }}
          flutter pub get

      - name: Find iOS directory
        id: find-ios
        run: |
          cd ${{ env.PROJECT_ROOT }}
          IOS_DIR=$(find . -name "ios" -type d -print -quit)
          if [ -n "$IOS_DIR" ]; then
            echo "IOS_PATH=$IOS_DIR" >> $GITHUB_ENV
          else
            echo "ERROR: No iOS directory found!"
            exit 1
          fi

      - name: Install CocoaPods
        run: |
          cd ${{ env.IOS_PATH }}
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build IPA
        run: |
          cd ${{ env.PROJECT_ROOT }}
          flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: ${{ env.PROJECT_ROOT }}/build/ios/ipa/*.ipa
