name: Build iOS IPA

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # يسمح بتشغيل العملية يدوياً

jobs:
  build-ipa:
    runs-on: macos-latest # ضروري لبناء iOS
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter (3.32.5)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: "stable"
          cache: true
          cache-key: flutter-packages
          cache-path: ${{ runner.temp }}/flutter_cache

      - name: Verify Flutter version
        run: flutter --version

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          sudo gem install cocoapods
          pod install --repo-update
        working-directory: ./ios

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build IPA (unsigned)
        run: flutter build ipa --release --no-codesign --export-options-plist=ExportOptions.plist

      - name: List build artifacts
        run: ls -la build/ios/ipa/

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
          retention-days: 7

      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: always() # دائمًا ارفع حتى لو فشل البناء
        with:
          name: build-logs
          path: |
            flutter.log
            build/**/*.log
