name: Build iOS IPA - Nuclear Option

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Nuclear cleanup
        run: |
          # احذف كل شيء متعلق بالبناء
          flutter clean
          rm -rf ios build .dart_tool .packages .flutter-plugins

          # أنشئ مشروع جديد مؤقت لاكتشاف الهيكل
          mkdir -p temp_project
          cd temp_project
          flutter create --template=app --org com.temp temp_app
          cd ..

          # انقل ملفات iOS الجديدة
          rm -rf ios
          cp -r temp_project/temp_app/ios .

          # انقل pubspec.yaml والمحتوى الأصلي
          cp pubspec.yaml temp_project/temp_app/
          cp -r lib temp_project/temp_app/
          cp -r assets temp_project/temp_app/ 2>/dev/null || true

          # استبدل المشروع المؤقت بالمشروع الأصلي
          rm -rf temp_project

          echo "✅ Nuclear cleanup completed"

      - name: Build with Flutter only
        run: |
          # دع Flutter يفعل كل شيء تلقائياً
          flutter pub get
          flutter build ipa --release --no-codesign

          echo "✅ Build completed without manual pod install"

      - name: Upload success artifact
        uses: actions/upload-artifact@v4
        with:
          name: success-ipa
          path: build/ios/ipa/*.ipa
