name: Build iOS IPA - Radical Solution

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Clean everything
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Get dependencies
        run: flutter pub get

      - name: Recreate iOS project completely
        run: |
          # احذف مجلد ios بالكامل
          rm -rf ios

          # أنشئ مشروع iOS جديد من الصفر
          flutter create --platforms=ios --ios-language=swift --org com.yourcompany .

          echo "✅ iOS project recreated completely"

      - name: Set iOS deployment target to 13.0
        run: |
          # تحديث Podfile إلى iOS 13.0
          if [ -f "ios/Podfile" ]; then
            sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/g' ios/Podfile
            echo "✅ Set iOS deployment target to 13.0"
          fi

          # أيضاً تحديث Info.plist إذا لزم الأمر
          if [ -f "ios/Runner/Info.plist" ]; then
            plutil -replace MinimumOSVersion -string "13.0" ios/Runner/Info.plist
            echo "✅ Updated Info.plist to iOS 13.0"
          fi

      - name: Build IPA directly (skip pod install)
        run: |
          # بناء IPA مباشرة - Flutter سيتعامل مع Podfile تلقائياً
          flutter build ipa --release --no-codesign --verbose

          echo "✅ IPA build completed successfully"

      - name: Check if IPA exists
        run: |
          if [ -f "build/ios/ipa/*.ipa" ]; then
            echo "✅ IPA file found:"
            ls -la build/ios/ipa/
          else
            echo "❌ No IPA file found"
            ls -la build/ || echo "No build directory"
            exit 1
          fi

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
          retention-days: 7

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            ~/Library/Logs/flutter.log
            build/**/*.log
