name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Clean and regenerate iOS files
        run: |
          flutter clean
          flutter pub get

          # احذف الملفات المسببة للمشاكل
          if [ -f "ios/Podfile" ]; then rm ios/Podfile; fi
          if [ -d "ios/Pods" ]; then rm -rf ios/Pods; fi
          if [ -f "ios/Podfile.lock" ]; then rm ios/Podfile.lock; fi

          # أنشئ ملفات iOS من جديد
          flutter build ios --no-codesign --release 2>/dev/null || true

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
