name: Build iOS IPA

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ipa:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Clean iOS files
        run: |
          flutter clean
          # تنظيف ملفات iOS القديمة
          if [ -f "ios/Podfile.lock" ]; then rm ios/Podfile.lock; fi
          if [ -d "ios/Pods" ]; then rm -rf ios/Pods; fi

      - name: Ensure iOS 13.0 platform
        run: |
          # أنشئ ملفات iOS إذا لم تكن موجودة
          if [ ! -f "ios/Podfile" ]; then
            flutter build ios --no-codesign --release 2>/dev/null || true
          fi

          # تأكد من أن platform هو 13.0
          if [ -f "ios/Podfile" ]; then
            # احذف أي platform قديم
            sed -i '' '/platform :ios/d' ios/Podfile
            # أضف platform جديد في الأعلى
            echo "platform :ios, '13.0'" | cat - ios/Podfile > temp && mv temp ios/Podfile
            echo "✅ Set iOS platform to 13.0"
            head -3 ios/Podfile
          else
            echo "❌ Podfile still not found!"
            exit 1
          fi

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/ios/ipa/*.ipa
